name: Release

## This workflow is limited only when a new tag is created
on:
  push:
    tags: ["*"]

## Set permissions to the github token
## https://github.com/softprops/action-gh-release#permissions 
permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: current
      - run: yarn install
      - run: yarn run build
      - run: yarn run pack:icons
      - uses: actions/upload-artifact@v7
        with:
          name: icons-package
          path: icons.*
          retention-days: 1
      - uses: actions/upload-artifact@v7
        with:
            name: icons-zip
            path: icons.zip
            retention-days: 1

  release:
    if: ${{ github.repository == 'jmjuanes/icons' }}
    runs-on: ubuntu-latest
    name: Release
    needs: [build]
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: icons-zip
      - uses: softprops/action-gh-release@v3
        with:
          files: icons.zip
          generate_release_notes: true
  
  publish:
    if: ${{ github.repository == 'jmjuanes/icons' }}
    runs-on: ubuntu-latest
    name: Publish
    needs: [build]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: current
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/download-artifact@v8
        with:
          name: icons-package
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
